version: '2'
services:
  nginx:
    image: nginx:alpine
    volumes:
     - ./site:/var/www/html:ro
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    networks:
      - backend

networks:
  backend:

volumes:
  data:
    driver: local
